import type { IconKind } from './apps';

export interface IconSelection {
	kind: IconKind | null;
	value: string | null;
}

export interface EmojiCategory {
	id: string;
	label: string;
	emojis: string[];
}

const PEOPLE = [
	'😀',
	'😃',
	'😄',
	'😁',
	'😆',
	'😅',
	'🤣',
	'😂',
	'🙂',
	'🙃',
	'🫠',
	'😉',
	'😊',
	'😇',
	'🥰',
	'😍',
	'🤩',
	'😘',
	'😗',
	'😚',
	'😙',
	'🥲',
	'😋',
	'😛',
	'😜',
	'🤪',
	'🤨',
	'🧐',
	'🤓',
	'😎',
	'🥸',
	'🤩',
	'🥳',
	'😏',
	'😒',
	'😞',
	'😔',
	'😟',
	'😕',
	'🙁',
	'😣',
	'😖',
	'😫',
	'😩',
	'🥺',
	'😢',
	'😭',
	'😤',
	'😠',
	'😡',
	'🤬',
	'🤯',
	'😳',
	'🥵',
	'🥶',
	'😱',
	'😨',
	'😰',
	'😥',
	'😓',
	'🫣',
	'🤗',
	'🤔',
	'🫡',
	'🤭',
	'🫢',
	'🫣',
	'🤫',
	'🤥',
	'😶',
	'🫥',
	'😐',
	'🫤',
	'😑',
	'😬',
	'🙄',
	'😯',
	'😦',
	'😧',
	'😮',
	'😲',
	'🥱',
	'😴',
	'🤤',
	'😪',
	'😷',
	'🤒',
	'🤕',
	'🤢',
	'🤮'
];

const NATURE = [
	'🐶',
	'🐱',
	'🐭',
	'🐹',
	'🐰',
	'🦊',
	'🐻',
	'🐼',
	'🐨',
	'🐯',
	'🦁',
	'🐮',
	'🐷',
	'🐸',
	'🐵',
	'🙈',
	'🙉',
	'🙊',
	'🐒',
	'🐔',
	'🐧',
	'🐦',
	'🐤',
	'🦆',
	'🦅',
	'🦉',
	'🦇',
	'🐺',
	'🐗',
	'🐴',
	'🌵',
	'🎄',
	'🌲',
	'🌳',
	'🌴',
	'🪴',
	'🌱',
	'🌿',
	'☘️',
	'🍀',
	'🍁',
	'🍂',
	'🍃',
	'🌷',
	'🌹',
	'🌻',
	'🌼',
	'🌸',
	'💐',
	'🍄'
];

const FOOD = [
	'🍏',
	'🍎',
	'🍐',
	'🍊',
	'🍋',
	'🍌',
	'🍉',
	'🍇',
	'🍓',
	'🫐',
	'🍈',
	'🍒',
	'🍑',
	'🥭',
	'🍍',
	'🥥',
	'🥝',
	'🍅',
	'🥑',
	'🍆',
	'🥔',
	'🥕',
	'🌽',
	'🌶️',
	'🫑',
	'🥒',
	'🥬',
	'🥦',
	'🍕',
	'🍔',
	'🍟',
	'🌭',
	'🍿',
	'🧂',
	'🥓',
	'🥚',
	'🍳',
	'🧇',
	'🥞',
	'🧈',
	'🍞',
	'🥐',
	'🥨',
	'🧀',
	'🥗',
	'🍝',
	'🍜',
	'🍲',
	'🍛',
	'🍣'
];

const ACTIVITY = [
	'⚽',
	'🏀',
	'🏈',
	'⚾',
	'🥎',
	'🎾',
	'🏐',
	'🏉',
	'🥏',
	'🎱',
	'🪀',
	'🏓',
	'🏸',
	'🏒',
	'🏑',
	'🥍',
	'🏏',
	'🪃',
	'🥅',
	'⛳',
	'🪁',
	'🏹',
	'🎣',
	'🤿',
	'🥊',
	'🥋',
	'🎽',
	'🛹',
	'🛼',
	'🛷',
	'⛸️',
	'🥌',
	'🎿',
	'⛷️',
	'🏂',
	'🪂',
	'🏋️',
	'🤼',
	'🤸',
	'⛹️',
	'🤺',
	'🤾',
	'🏌️',
	'🏇',
	'🧘',
	'🏄',
	'🏊',
	'🤽',
	'🚣',
	'🧗'
];

const TRAVEL = [
	'🚗',
	'🚕',
	'🚙',
	'🚌',
	'🚎',
	'🏎️',
	'🚓',
	'🚑',
	'🚒',
	'🚐',
	'🛻',
	'🚚',
	'🚛',
	'🚜',
	'✈️',
	'🛩️',
	'🛫',
	'🛬',
	'🚀',
	'🛸',
	'🚁',
	'🛶',
	'⛵',
	'🚤',
	'🛥️',
	'🛳️',
	'⛴️',
	'🚢',
	'⚓',
	'⛽'
];
const OBJECTS = [
	'💡',
	'🔦',
	'🕯️',
	'🪔',
	'🧯',
	'🛢️',
	'💸',
	'💵',
	'💴',
	'💶',
	'💷',
	'🪙',
	'💰',
	'💳',
	'💎',
	'⚖️',
	'🪜',
	'🧰',
	'🪛',
	'🔧',
	'🔨',
	'⚒️',
	'🛠️',
	'⛏️',
	'🪚',
	'🔩',
	'⚙️',
	'🪤',
	'🧱',
	'⛓️'
];
const SYMBOLS = [
	'✅',
	'☑️',
	'✔️',
	'❌',
	'❎',
	'➕',
	'➖',
	'➗',
	'✖️',
	'🟰',
	'💯',
	'🔴',
	'🟠',
	'🟡',
	'🟢',
	'🔵',
	'🟣',
	'⚫',
	'⚪',
	'🟤',
	'🚩',
	'🏁',
	'🏳️',
	'🏴',
	'🏳️‍🌈',
	'🔶',
	'🔷',
	'🔸',
	'🔹',
	'🔺'
];
const FLAGS = [
	'🏳️',
	'🏴',
	'🏁',
	'🚩',
	'🏳️‍🌈',
	'🏳️‍⚧️',
	'🏴‍☠️',
	'🇺🇸',
	'🇬🇧',
	'🇩🇪',
	'🇫🇷',
	'🇮🇹',
	'🇪🇸',
	'🇯🇵',
	'🇰🇷',
	'🇨🇳',
	'🇧🇷',
	'🇨🇦',
	'🇦🇺',
	'🇮🇳'
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
	{ id: 'people', label: 'People', emojis: PEOPLE },
	{ id: 'nature', label: 'Nature', emojis: NATURE },
	{ id: 'food', label: 'Food', emojis: FOOD },
	{ id: 'activity', label: 'Activity', emojis: ACTIVITY },
	{ id: 'travel', label: 'Travel', emojis: TRAVEL },
	{ id: 'objects', label: 'Objects', emojis: OBJECTS },
	{ id: 'symbols', label: 'Symbols', emojis: SYMBOLS },
	{ id: 'flags', label: 'Flags', emojis: FLAGS }
];

export const ALL_EMOJIS: string[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);

export const ICON_NAMES = [
	'box',
	'container',
	'server',
	'database',
	'globe',
	'cloud',
	'cpu',
	'zap',
	'rocket',
	'layers',
	'package',
	'git-branch',
	'terminal',
	'monitor',
	'smartphone',
	'wifi',
	'shield',
	'lock',
	'key',
	'bell',
	'star',
	'heart',
	'flag',
	'tag',
	'bookmark',
	'settings',
	'wrench',
	'hammer',
	'palette',
	'image',
	'music',
	'video',
	'file-text',
	'folder'
];

const RECENT_KEY = 'smoothie_recent_icons';

export function getRecentIcons(): IconSelection[] {
	try {
		const raw = localStorage.getItem(RECENT_KEY);
		if (!raw) return [{ kind: 'emoji', value: '⚽' }];
		const parsed = JSON.parse(raw) as IconSelection[];
		return parsed.filter((i) => i.value).slice(0, 24);
	} catch {
		return [{ kind: 'emoji', value: '⚽' }];
	}
}

export function pushRecentIcon(sel: IconSelection): IconSelection[] {
	if (!sel.value || !sel.kind) return getRecentIcons();
	try {
		const current = getRecentIcons().filter((i) => !(i.kind === sel.kind && i.value === sel.value));
		const next = [sel, ...current].slice(0, 24);
		localStorage.setItem(RECENT_KEY, JSON.stringify(next));
		return next;
	} catch {
		return getRecentIcons();
	}
}

export function randomEmoji(): string {
	return ALL_EMOJIS[Math.floor(Math.random() * ALL_EMOJIS.length)];
}

const EMOJI_KEYWORDS: Record<string, string> = {
	'😀': 'grinning happy smile face',
	'😃': 'grinning big eyes happy smile',
	'😄': 'grin smiling eyes laugh happy',
	'😁': 'beaming grin teeth happy',
	'😆': 'squint laugh happy satisfied',
	'😅': 'grin sweat nervous laugh',
	'🤣': 'rolling floor laughing rofl lol',
	'😂': 'tears joy laugh lol happy cry',
	'🙂': 'slight smile happy',
	'🙃': 'upside down silly sarcastic',
	'🫠': 'melting hot',
	'😉': 'winking joke flirt',
	'😊': 'blush smile happy shy',
	'😇': 'angel halo innocent',
	'🥰': 'hearts love smiling',
	'😍': 'heart eyes love crush',
	'🤩': 'star eyes excited wow',
	'😘': 'kiss love wink',
	'😗': 'kiss whistling',
	'😚': 'kiss eyes closed love',
	'😙': 'kiss smile love',
	'🥲': 'tear smile touched grateful',
	'😋': 'yummy tongue delicious hungry',
	'😛': 'tongue playful',
	'😜': 'wink tongue joke crazy',
	'🤪': 'crazy zany wild party',
	'🤨': 'raised eyebrow suspicious doubt',
	'🧐': 'monocle inspect fancy',
	'🤓': 'nerd geek glasses smart',
	'😎': 'cool sunglasses confident',
	'🥸': 'disguise glasses incognito',
	'🥳': 'party celebrate birthday horn',
	'😏': 'smirk smug flirt',
	'😒': 'unamused annoyed bored',
	'😞': 'disappointed sad',
	'😔': 'pensive sad sorry',
	'😟': 'worried concerned',
	'😕': 'confused unsure',
	'🙁': 'frown sad',
	'😣': 'persevere struggle',
	'😖': 'confounded upset',
	'😫': 'tired exhausted',
	'😩': 'weary tired fed up',
	'🥺': 'pleading puppy eyes beg sorry',
	'😢': 'cry tear sad',
	'😭': 'sob bawling cry tears sad',
	'😤': 'triumph steam frustrated proud',
	'😠': 'angry mad annoyed',
	'😡': 'rage red angry pouting',
	'🤬': 'swearing cursing angry',
	'🤯': 'exploding mind blown wow',
	'😳': 'flushed embarrassed blush',
	'🥵': 'hot sweating heat thirsty',
	'🥶': 'cold freezing ice',
	'😱': 'scream shocked fear horror',
	'😨': 'fearful scared worried',
	'😰': 'anxious sweat nervous',
	'😥': 'sad relieved sweat',
	'😓': 'sweat downcast tired work',
	'🫣': 'peek hide shy',
	'🤗': 'hug embrace thanks',
	'🤔': 'thinking hmm wonder',
	'🫡': 'salute respect',
	'🤭': 'giggle snicker oops',
	'🫢': 'gasp surprise shock',
	'🤫': 'shush quiet secret',
	'🤥': 'lying liar pinocchio',
	'😶': 'no mouth silent speechless',
	'🫥': 'dotted invisible',
	'😐': 'neutral meh deadpan',
	'🫤': 'diagonal mouth skeptical',
	'😑': 'expressionless annoyed',
	'😬': 'grimace awkward nervous',
	'🙄': 'roll eyes annoyed',
	'😯': 'hushed surprised wow',
	'😦': 'frown open worried',
	'😧': 'anguished shock',
	'😮': 'open mouth wow surprise',
	'😲': 'astonished shocked amazed',
	'🥱': 'yawn tired bored',
	'😴': 'sleeping snore tired',
	'🤤': 'drool hungry',
	'😪': 'sleepy tired',
	'😷': 'mask sick covid ill',
	'🤒': 'thermometer sick fever ill',
	'🤕': 'bandage hurt injured',
	'🤢': 'nauseated sick gross',
	'🤮': 'vomit sick puke',
	'🐶': 'dog puppy pet',
	'🐱': 'cat kitten pet',
	'🐭': 'mouse rat',
	'🐹': 'hamster pet',
	'🐰': 'rabbit bunny easter',
	'🦊': 'fox',
	'🐻': 'bear teddy',
	'🐼': 'panda',
	'🐨': 'koala',
	'🐯': 'tiger',
	'🦁': 'lion king',
	'🐮': 'cow moo milk',
	'🐷': 'pig oink',
	'🐸': 'frog toad',
	'🐵': 'monkey',
	'🙈': 'see no evil monkey',
	'🙉': 'hear no evil monkey',
	'🙊': 'speak no evil monkey',
	'🐒': 'monkey',
	'🐔': 'chicken hen',
	'🐧': 'penguin',
	'🐦': 'bird',
	'🐤': 'chick baby bird',
	'🦆': 'duck',
	'🦅': 'eagle bird',
	'🦉': 'owl wise',
	'🦇': 'bat vampire halloween',
	'🐺': 'wolf',
	'🐗': 'boar pig',
	'🐴': 'horse',
	'🌵': 'cactus desert',
	'🎄': 'christmas tree holiday xmas',
	'🌲': 'evergreen pine tree',
	'🌳': 'tree deciduous',
	'🌴': 'palm beach tropical summer',
	'🪴': 'potted plant',
	'🌱': 'seedling sprout grow',
	'🌿': 'herb leaf',
	'☘️': 'shamrock luck irish',
	'🍀': 'clover luck',
	'🍁': 'maple leaf fall autumn canada',
	'🍂': 'fallen leaves autumn fall',
	'🍃': 'leaves wind',
	'🌷': 'tulip flower spring',
	'🌹': 'rose love flower',
	'🌻': 'sunflower',
	'🌼': 'blossom flower',
	'🌸': 'cherry blossom sakura spring',
	'💐': 'bouquet flowers gift',
	'🍄': 'mushroom toadstool',
	'🍏': 'green apple fruit',
	'🍎': 'red apple fruit',
	'🍐': 'pear fruit',
	'🍊': 'orange tangerine fruit',
	'🍋': 'lemon citrus',
	'🍌': 'banana fruit',
	'🍉': 'watermelon fruit summer',
	'🍇': 'grapes wine fruit',
	'🍓': 'strawberry berry fruit',
	'🫐': 'blueberries berry',
	'🍈': 'melon cantaloupe',
	'🍒': 'cherries berry',
	'🍑': 'peach',
	'🥭': 'mango fruit',
	'🍍': 'pineapple tropical',
	'🥥': 'coconut tropical',
	'🥝': 'kiwi fruit',
	'🍅': 'tomato',
	'🥑': 'avocado toast',
	'🍆': 'eggplant aubergine',
	'🥔': 'potato',
	'🥕': 'carrot vegetable',
	'🌽': 'corn maize',
	'🌶️': 'chili pepper hot spicy',
	'🫑': 'bell pepper',
	'🥒': 'cucumber pickle',
	'🥬': 'greens lettuce kale salad',
	'🥦': 'broccoli vegetable',
	'🍕': 'pizza slice cheese',
	'🍔': 'burger hamburger fast food',
	'🍟': 'fries fast food',
	'🌭': 'hot dog',
	'🍿': 'popcorn movie snack',
	'🧂': 'salt',
	'🥓': 'bacon breakfast',
	'🥚': 'egg breakfast',
	'🍳': 'fried egg breakfast cooking',
	'🧇': 'waffle breakfast',
	'🥞': 'pancakes breakfast',
	'🧈': 'butter',
	'🍞': 'bread toast',
	'🥐': 'croissant french breakfast',
	'🥨': 'pretzel',
	'🧀': 'cheese',
	'🥗': 'salad healthy green',
	'🍝': 'spaghetti pasta italian',
	'🍜': 'noodles ramen soup',
	'🍲': 'stew pot soup food',
	'🍛': 'curry rice',
	'🍣': 'sushi japanese fish',
	'⚽': 'soccer football sport ball',
	'🏀': 'basketball sport ball',
	'🏈': 'american football sport',
	'⚾': 'baseball sport ball',
	'🥎': 'softball sport',
	'🎾': 'tennis sport ball',
	'🏐': 'volleyball sport',
	'🏉': 'rugby sport',
	'🥏': 'frisbee disc',
	'🎱': 'pool billiards 8 ball game',
	'🪀': 'yoyo toy',
	'🏓': 'ping pong table tennis',
	'🏸': 'badminton',
	'🏒': 'ice hockey sport',
	'🏑': 'field hockey',
	'🥍': 'lacrosse',
	'🏏': 'cricket',
	'🪃': 'boomerang',
	'🥅': 'goal net sport',
	'⛳': 'golf flag',
	'🪁': 'kite fly',
	'🏹': 'bow arrow archery',
	'🎣': 'fishing rod fish',
	'🤿': 'diving mask snorkel swim',
	'🥊': 'boxing gloves fight sport',
	'🥋': 'martial arts karate judo',
	'🎽': 'running shirt sport',
	'🛹': 'skateboard',
	'🛼': 'roller skate',
	'🛷': 'sled snow',
	'⛸️': 'ice skate winter',
	'🥌': 'curling winter',
	'🎿': 'skis snow winter',
	'⛷️': 'skier snow winter',
	'🏂': 'snowboard snow winter',
	'🪂': 'parachute skydive',
	'🏋️': 'weightlifting gym lift strong',
	'🤼': 'wrestling fight',
	'🤸': 'cartwheel gymnastics',
	'⛹️': 'basketball bounce sport',
	'🤺': 'fencing sword',
	'🤾': 'handball',
	'🏌️': 'golf',
	'🏇': 'horse racing',
	'🧘': 'yoga meditation lotus calm',
	'🏄': 'surf surfing wave beach',
	'🏊': 'swim swimming pool',
	'🤽': 'water polo swim',
	'🚣': 'rowboat canoe kayak',
	'🧗': 'climbing rock mountain',
	'🚗': 'car red drive',
	'🚕': 'taxi cab',
	'🚙': 'suv car',
	'🚌': 'bus',
	'🚎': 'trolleybus',
	'🏎️': 'race car f1 fast',
	'🚓': 'police car cop',
	'🚑': 'ambulance emergency',
	'🚒': 'fire truck engine',
	'🚐': 'minibus van',
	'🛻': 'pickup truck',
	'🚚': 'truck delivery',
	'🚛': 'semi truck highway',
	'🚜': 'tractor farm',
	'✈️': 'airplane plane flight travel',
	'🛩️': 'small airplane flight',
	'🛫': 'takeoff departure flight plane',
	'🛬': 'landing arrival flight plane',
	'🚀': 'rocket space launch ship',
	'🛸': 'ufo alien spaceship',
	'🚁': 'helicopter',
	'🛶': 'canoe boat',
	'⛵': 'sailboat sailing yacht',
	'🚤': 'speedboat motorboat',
	'🛥️': 'motor boat yacht',
	'🛳️': 'cruise ship vacation',
	'⛴️': 'ferry boat',
	'🚢': 'ship boat',
	'⚓': 'anchor navy ship',
	'⛽': 'fuel gas pump station',
	'💡': 'bulb idea light',
	'🔦': 'flashlight torch light',
	'🕯️': 'candle light',
	'🪔': 'diya lamp',
	'🧯': 'extinguisher fire',
	'🛢️': 'oil barrel drum',
	'💸': 'money wings spend cash',
	'💵': 'dollar money cash',
	'💴': 'yen money cash',
	'💶': 'euro money cash',
	'💷': 'pound money cash',
	'🪙': 'coin money',
	'💰': 'money bag rich dollar',
	'💳': 'credit card payment',
	'💎': 'diamond gem jewel',
	'⚖️': 'scale balance justice',
	'🪜': 'ladder',
	'🧰': 'toolbox tools',
	'🪛': 'screwdriver tool',
	'🔧': 'wrench tool fix',
	'🔨': 'hammer tool',
	'⚒️': 'hammer pick tools work',
	'🛠️': 'tools hammer wrench fix',
	'⛏️': 'pick mining',
	'🪚': 'saw carpentry',
	'🔩': 'nut bolt',
	'⚙️': 'gear settings',
	'🪤': 'mousetrap',
	'🧱': 'bricks wall',
	'⛓️': 'chains link',
	'✅': 'check green done',
	'☑️': 'checkbox ballot check vote',
	'✔️': 'check mark done',
	'❌': 'cross wrong no',
	'❎': 'cross mark no',
	'➕': 'plus add',
	'➖': 'minus subtract',
	'➗': 'divide',
	'✖️': 'multiply x',
	'🟰': 'equals',
	'💯': 'hundred 100 perfect score',
	'🔴': 'red circle',
	'🟠': 'orange circle',
	'🟡': 'yellow circle',
	'🟢': 'green circle',
	'🔵': 'blue circle',
	'🟣': 'purple circle',
	'⚫': 'black circle',
	'⚪': 'white circle',
	'🟤': 'brown circle',
	'🚩': 'red flag',
	'🏁': 'checkered flag race finish',
	'🏳️': 'white flag surrender',
	'🏴': 'black flag',
	'🏳️‍🌈': 'rainbow pride flag',
	'🔶': 'orange diamond',
	'🔷': 'blue diamond',
	'🔸': 'small orange diamond',
	'🔹': 'small blue diamond',
	'🔺': 'red triangle up',
	'🏳️‍⚧️': 'transgender pride flag',
	'🏴‍☠️': 'pirate flag',
	'🇺🇸': 'usa america flag',
	'🇬🇧': 'uk britain england flag',
	'🇩🇪': 'germany deutschland flag',
	'🇫🇷': 'france flag',
	'🇮🇹': 'italy flag',
	'🇪🇸': 'spain flag',
	'🇯🇵': 'japan flag',
	'🇰🇷': 'korea flag',
	'🇨🇳': 'china flag',
	'🇧🇷': 'brazil flag',
	'🇨🇦': 'canada flag',
	'🇦🇺': 'australia flag',
	'🇮🇳': 'india flag'
};

const CATEGORY_BY_EMOJI = new Map<string, string>();
for (const category of EMOJI_CATEGORIES) {
	for (const emoji of category.emojis) {
		if (!CATEGORY_BY_EMOJI.has(emoji)) CATEGORY_BY_EMOJI.set(emoji, category.label);
	}
}

export function searchEmojis(query: string): string[] | null {
	const q = query.trim().toLowerCase();
	if (!q) return null;
	const direct = ALL_EMOJIS.filter((emoji) => emoji.includes(query.trim()));
	if (direct.length > 0) return direct.slice(0, 120);
	const words = q.split(/\s+/);
	return ALL_EMOJIS.filter((emoji) => {
		const haystack =
			`${EMOJI_KEYWORDS[emoji] ?? ''} ${CATEGORY_BY_EMOJI.get(emoji) ?? ''}`.toLowerCase();
		return words.every((word) => haystack.includes(word));
	}).slice(0, 120);
}
